### ISSUE TITLE
Protect against placing entities

### ISSUE THREAD

**Issue by CLtheman1** [mt-mods/protector#11]
This should work on protecting against players being able to place entities like animals or vehicles to keep griefers from placing a bunch of them in a bunch of entities in a protected space to lag someone.

Might wanna take note of Apercy's mods, because I was told Apercy might not be keen of placing code in his mods to prevent planes from being placed in protected areas, but I don't know.

**Comment by S-S-X** [comment]
This should be done by doing `minetest.is_protected(pos, name)` on mod that is placing, digging, building, whatever.
Protector mods should not allow or prevent any specific actions by themselves.

Minetest engine documentation for protection check:

* `minetest.is_protected(pos, name)`: returns boolean
    * Returning `true` restricts the player `name` from modifying (i.e. digging,
       placing) the node at position `pos`.
    * `name` will be `""` for non-players or unknown players.

**Comment by S-S-X** [comment]
Marked as "wontfix" because if custom overrides for mod is done here it will just cause confusion when some protection mods work and some wont, protections handling would depend on mod loading order / protection check implementation order and would require weird hacks to work correctly even with just this specific protection mod.

I would suggest having configuration for protection in Apercy's mods if some wants to have protection and some wont.

Could be done for example with mod specific wrapper but of course up to mod author:
```lua
function my_mod.is_protected(pos, name)
    if minetest.settings:get_bool("my_mod.use_protection", false) then
        return minetest.is_protected(pos, name)
    end
end
```
or cached configuration:
```lua
if minetest.settings:get_bool("my_mod.use_protection", false) then
    function my_mod.is_protected(pos, name)
        return minetest.is_protected(pos, name)
    end
else
    function my_mod.is_protected(pos, name)
        return false
    end
end
```

Leaving issue open for possible discussion about implementation details or further discussion about original request.

**Comment by S-S-X** [comment]
So far no follow up discussion / questions so closing this.
If this is still relevant I would recommend opening issue in Apercy's mod issue tracker.
