### ISSUE TITLE
Idea: Prevent protecting 'fresh bones' 

### ISSUE THREAD

**Issue by monk-afk** [mt-mods/protector#12]
In an effort to discourage killing to protect bones until the assailant can collect the items, a player cannot place protector within a distance of bones they do not own (fresh bones).

Is enabled if setting `protector_bones` is true. During `check_overlap`, does `find_nodes_in_area` for bones within a distance of the pointed position (`2 * protector_radius`, one diameter). Build table of non-empty owner strings from bones meta. If an owner name does not match the placer's name, return itemstack to placer.

The concept is currently included in [this fork](https://github.com/monk-afk/protector). Let me know what you think. Thanks.

**Comment by BuckarooBanzay** [comment]
The "fresh" bones do already have a feature to let the owner take items before they get old: https://github.com/minetest/minetest_game/blob/master/mods/bones/init.lua#L65-L70

How does that affect this feature?

**Comment by monk-afk** [comment]
The suggestion is of a setting to toggle players' ability to place protection blocks near another player's fresh bones. Protecting fresh bones and burying it would prevent the bones owner from retrieving their items. The code does not affect the player's ability to collect the items from their own fresh bones.

**Comment by S-S-X** [comment]
This idea wont work if bones get placed into already protected area. Instead of adding half baked and confusing feature into protection mods should make sure that activating bones do not do generic protection checks but only freshness and owner check or no checks at all.

**Comment by monk-afk** [comment]
The idea is about '_placing protector block near fresh bones_', which affects the Protector mod. It is not about 'dropping bones in a protected area', a function not included in the Protector mod. Nowhere in this idea is it suggesting making changes to bones mod. Could you clarify which part is confusing you to say it is half-baked? You could also simply close the ticket if the idea does not interest you.

**Comment by S-S-X** [comment]
> The idea is about 'placing protector block near fresh bones'

Noted that idea is about preventing placement of undiggable nodes around bones.

> Could you clarify which part is confusing you to say it is half-baked?

Considering complexity I think it might not change situation enough to really be worth it as is because players can easily make bones inaccessible if they want to for example by

* just covering bones with nodes that have self protection (locked chests, doors, in many cases a lot of other stuff too)
* digging a bit and then protecting
* nasty liquids and few well placed protectors
* other protections
* depending on installed mods many other ways

I just think this might not be that useful as in addition to being incomplete it also allows easily blocking legit protection of fairly large areas. Technical solution would be nice but restriction that is too easy to avoid might be better implemented through server rules until solution with better coverage is available. Do you happen to have ideas for such solution / towards it?

> You could also simply close the ticket if the idea does not interest you

Technically I could but some discussion, as long as something is added, could be useful and might help finding good solution with even better coverage.

**Comment by monk-afk** [comment]
You make valid points that have yet to be considered.

For nodes with self protection, as in nodes which do not rely on the protector:protect node for ownership, the first thing which comes to mind is: `register_on_place` and `get_meta` could be used to determine if the placed node has an owner reference, then continue with `find_nodes_in_area` to find bones with owner meta within a pos determined by the placed node.

However, I acknowledge this is a sub-optimal solution.

**Comment by OgelGames** [comment]
Maybe the solution is not to prevent bones being obstructed, but instead to find a way for players collect their bones even when they can't interact with them, a chat command maybe?

**Comment by monk-afk** [comment]
Interesting and original proposal. So far i only have code to prevent protector place near bones, and prevent bones drop in protect area. 
What you're suggesting could be introduced as a second function to a 'return-to-bones' mod. Thanks for the feedback

**Comment by monk-afk** [comment]
I'm going to withdraw from this idea discussion, it's apparent I was overly ambitious to solve a problem which doesn't exist most of the time. 
I will continue using the half-baked idea on my server for the players.
Thanks again for your feedback, I appreciate getting details to clear up my ignorance. 
https://github.com/monk-afk/protector/commit/a8523abbd17f71485f490a1fa0bcc71208da296d
